(cl:in-package battery_state-msg)
(cl:export '(HEADER-VAL
          HEADER
          DEVICE_NAME-VAL
          DEVICE_NAME
          PARTITIONS-VAL
          PARTITIONS
          SYSTEM_SIZE-VAL
          SYSTEM_SIZE
          CPU_PROCESSOR-VAL
          CPU_PROCESSOR
          FREE_SPACE-VAL
          FREE_SPACE
          RAM_SIZE-VAL
          RAM_SIZE
          USED_RAM-VAL
          USED_RAM
          AVAILABLE_RAM-VAL
          AVAILABLE_RAM
          FREQUENCY-VAL
          FREQUENCY
          CPU_TEMP-VAL
          CPU_TEMP
          CORE_TEMP-VAL
          CORE_TEMP
          CPU_MODEL_NAME-VAL
          CPU_MODEL_NAME
          USER_NAME-VAL
          USER_NAME
          LINUX_VERSION-VAL
          LINUX_VERSION
))